[project]
name = "commit-me"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.5.0",
    "rich>=15.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
    "ty>=0.0.80",
]


[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py311"

exclude = [".git", "__pycache__", "styles", ".vscode", ".github"]

[tool.ruff.lint]
select = [
	"F",
	"E",
	"W",
	"N",
	"UP",
	"ANN",
	"BLE",
	"A",
	"COM",
	"C4",
	"DTZ",
	"Q",
	"SLF",
	"SIM",
	"PTH",
	"I",
]
ignore = ["COM812"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = false
line-ending = "auto"
